api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('products', views.ProductViewSet)
router.register('categories', views.CategoryViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('add_to_cart/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/update', views.UpdateCartView.as_view(), name='update_cart'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('django-rq/', include('django_rq.urls')),
]

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:question_id>/results', views.results, name='results'),
    path('create', views.create_question, name='create'),
]

polls/models.py
from django.contrib import admin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone


class Question(models.Model):
    class Status(models.TextChoices):
        NEW = 'NW', _('New')
        REJECTED = 'RJ', _('Rejected')
        APPROVED = 'AP', _('Approved')

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(verbose_name='Publication date')
    status = models.CharField(max_length=2, choices=Status, default=Status.NEW)
    view_count = models.IntegerField(default=0)

    @admin.display(
        boolean=True,
        description='Published recently?',
        ordering='pub_date'
    )
    def was_published_recently(self):
        if not self.pub_date:
            return False
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, related_name='choices',
                                 on_delete=models.CASCADE)

    @admin.display(ordering='question__question_text', description='Question Text')
    def get_question_text(self):
        return self.question.question_text

    def __str__(self):
        return f'{self.question.question_text} - {self.choice_text}'

polls/forms.py
from django import forms
from django.utils import timezone


class QuestionForm(forms.Form):
    question_text = forms.CharField(label='Question', max_length=100)
    publication_date = forms.DateField(initial=timezone.now().date(),
                                       widget=forms.SelectDateWidget())
    choices = forms.CharField(label='Choices', widget=forms.Textarea)

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.utils import timezone
from django.views.decorators.cache import cache_page

from .jobs import update_question_view_count
from .models import Question, Choice
from .forms import QuestionForm


@cache_page(60)
def index(request):
    questions = Question.objects \
                    .filter(status=Question.Status.APPROVED,
                            pub_date__lte=timezone.now()) \
                    .filter() \
                    .order_by('-pub_date')[:5]
    context = {'latest_question_list': questions}
    return render(request, 'polls/index.html', context)


def detail(request, question_id: int):
    question = get_object_or_404(Question, id=question_id,
                                 status=Question.Status.APPROVED,
                                 pub_date__lte=timezone.now())
    update_question_view_count.delay(question)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)

def vote(request, question_id: int):
    question = get_object_or_404(Question, id=question_id,
                                 status=Question.Status.APPROVED,
                                 pub_date__lte=timezone.now())
    try:
        selected_choice = question.choices.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'error_message': "You didn't select a choice",
            'question': question,
        })
    selected_choice.votes += 1
    selected_choice.save()
    return redirect('polls:results', question.id)


def results(request, question_id: int):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}
    return render(request, 'polls/results.html', context)


def create_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data['question_text']
            pub_date = form.cleaned_data['publication_date']
            question = Question(question_text=question_text, pub_date=pub_date)
            question.save()
            for choice_text in form.cleaned_data['choices'].split('\n'):
                question.choices.create(choice_text=choice_text, votes=0)
            messages.success(request, 'Your question is added and will be '
                                      'displayed once reviewed by administrator')
            return redirect('polls:index')
    else:
        form = QuestionForm()
    return render(request, 'polls/create_question.html', {'form': form})

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}Polls APP{% endblock %}</title>
</head>
<body>
    <div class="hstack gap-3">
        <a href="{% url 'polls:index' %}">
            <img src="https://netstorage.ringcentral.com/appext/logo/kNku72HNQPWCo-uLCKS4Hw~wCZbXGy1Qu-z3dzQ3U_j7Q/b8e47126-bf75-41df-bbf0-844db0a925a4.png" height="40"/>
        </a>
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-danger"/>
            </form>
        {% else %}
            <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
        {% endif %}
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</body>
</html>

polls/templates/polls/create_question.html
{% extends 'polls/base.html' %}

{% block body %}
    <form action="{% url 'polls:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create"/>
    </form>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}Poll{% endblock %}

{% block body %}
      <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choices.all|dictsort:'choice_text' %}
                <input type="radio" name="choice" value="{{ choice.id }}"
                       id="choice-{{ forloop.counter }}"/>
                <label for="choice-{{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote"/>
    </form>
    {{ question.view_count }} &#128065;<br>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block body %}
    {% if latest_question_list %}
        <h1>Questions:</h1>
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <p>
        <a href="{% url 'polls:create' %}" class="btn btn-primary">Create new question</a>
    </p>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}Poll results{% endblock %}

{% block body %}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choices.all|dictsort:'choice_text' %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
{% endblock %}