api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('products', views.ProductViewSet)
router.register('categories', views.CategoryViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('add_to_cart/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/update', views.UpdateCartView.as_view(), name='update_cart'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('django-rq/', include('django_rq.urls')),
]

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'
urlpatterns = [
    path('products/', views.products_view, name='products'),
    path('product/<int:product_id>', views.product_detail, name='product_detail'),
    path('add_to_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import QuerySet
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class OrderEntry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='+')
    count = models.IntegerField(default=0)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_entries')

    def __str__(self):
        return f'{self.product} - {self.count}'


class OrderStatus(models.TextChoices):
    INITIAL = "IN", _("Initial")
    COMPLETED = "CO", _("Completed")
    DELIVERED = "DE", _("Delivered")


class Order(models.Model):
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=2, choices=OrderStatus.choices,
                              default=OrderStatus.INITIAL)
    order_entries: QuerySet[OrderEntry]

    def __str__(self):
        return f'id:{self.id} - {self.profile} - {self.status}'

    def add_product(self, product: Product):
        order_entry: OrderEntry = self.order_entries.filter(product=product).first()
        if not order_entry:
            order_entry = self.order_entries.create(product=product, count=0)
        order_entry.count += 1
        order_entry.save()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL,
                                null=True, blank=True, default=None)
    shopping_cart = models.OneToOneField(Order, on_delete=models.SET_NULL,
                                         null=True, blank=True, related_name='+')

    def __str__(self):
        return str(self.user)

shop/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Order, OrderEntry


def products_view(request):
    context = {'products': Product.objects.all()}
    return render(request, 'shop/products.html', context)


def product_detail(request, product_id: int):
    context = {'product': get_object_or_404(Product, id=product_id)}
    return render(request, 'shop/product_detail.html', context)


@login_required
def add_to_cart(request: HttpRequest, product_id: int):
    if request.method == 'POST':
        product = get_object_or_404(Product, id=product_id)
        request.user.profile.shopping_cart.add_product(product)
    return redirect('shop:product_detail', product_id)

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
</head>
<body>
    <div class="hstack gap-3">
        <a href="{% url 'shop:products' %}">Products</a>
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-danger"/>
            </form>
        {% else %}
            <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
        {% endif %}
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
    {% endif %}

    {% block body %}{% endblock %}
</body>
</html>

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block body %}
    <h1>{{ product.name }}</h1>

    <p>Category: {{ product.category.name }}</p>

    <p>Price: {{ product.price }}$</p>

    <p>Description: {{product.description}}</p>

    <form action="{% url 'shop:add_to_cart' product.id %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-info" value="Add to cart"/>
    </form>
{% endblock %}

shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block body %}
    <h1>Products:</h1>

    <ul>
        {% for product in products %}
            <li>
                <a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}